### ISSUE TITLE
FTP Host Error

### ISSUE THREAD

**Issue by charleswebmaster** [cumulusclips/cumulusclips#11]
On Installation, i see this error "Unable to perform database portion of installation. The following error occurred:

Unable to connect to FTP host ()"

Please Help
![capture](https://user-images.githubusercontent.com/24209745/40583170-ddaec6cc-6180-11e8-948e-26c25fa20594.PNG)

**Comment by bruhmoment0lol** [comment]
How did you fix the issue? I'm also trying to figure this out
