### ISSUE TITLE
Private videos not visible to user who owns them

### ISSUE THREAD

**Issue by funnymanva** [cumulusclips/cumulusclips#14]
When a video is marked private it is not visible in the video list, with or without a category selected, to the owner of those videos. It looks like the SQL query contains only private = '0' with no check if a user is logged in to include those videos. This is true for both queries when selecting a category or not.

**Comment by mtado06** [comment]
It was actually like that by design. The intended way to see private videos by the owner is by accessing them via the My Account -> My Videos. Is that not working?

**Comment by funnymanva** [comment]
When I go to my account I see no videos for that user either. Older versions did use to include them in the main browse list if they belonged to that user.

Carlton
