### ISSUE TITLE
Possible problem in UserMapper.php

### ISSUE THREAD

**Issue by phdabel** [cumulusclips/cumulusclips#3]
Dears,

I am developing a LDAP plugin based in others that was created for cumulus clips.
When I tried to insert information about first and last name of the new user I observed that the first name was not inserted in the record.
Then I saw that in the UserMapper.php during the creation of the record (line 115) it is passed a parameter $user->duration that does not exist in the model User.php.

Is this an error?

**Comment by mtado06** [comment]
Yes it is. Thank you for reporting it.
