### ISSUE TITLE
php-mysql pdo

### ISSUE THREAD

**Issue by taozhijiang** [cumulusclips/cumulusclips#5]
Hello, I am running on Ubuntu 16.04 with php 7.0

It can not be installed with error:

[Sat Feb 11 19:27:32.657063 2017] [:error] [pid 2635] [client 172.16.20.1:53802] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /home/user/www/cctvbxy.com/cc-install/database.php:76\nStack trace:\n#0 /home/user/www/cctvbxy.com/cc-install/index.php(37): include_once()\n#1 {main}\n  thrown in /home/user/www/cctvbxy.com/cc-install/database.php on line 76, referer: http://cctvbxy.com/cc-install/?database
[Sat Feb 11 19:31:08.850988 2017] [:error] [pid 2636] [client 172.16.20.1:53857] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /home/user/www/cctvbxy.com/cc-install/database.php:76\nStack trace:\n#0 /home/user/www/cctvbxy.com/cc-install/index.php(37): include_once()\n#1 {main}\n  thrown in /home/user/www/cctvbxy.com/cc-install/database.php on line 76, referer: http://cctvbxy.com/cc-install/?database

Please help me check this. thanks.

**Comment by mtado06** [comment]
This has been resolved in version 2.5. The installer now uses PHP PDO instead of the mysql_* functions.
